sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t kakkarnit/docker-react .

script:
  - docker run -e CI=true kakkarnit/docker-react npm run test -- --coverage
#test comment